# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad9c88a53ae0ec40fc4e56d53296a84c82ea647bbdd010ed3c2efb5edf2a6a134b94b1fff32ea21c029ace6a96d54623efbf99aa8bd55be37b3033f4d9d1c304

test:
  secret_key_base: fe7c8d019c18cc1fc44e25606f986acf5825c49dd8a42fc1b765dd9dde53954233ac11f7a85ed0563cd7f366aa4d3a69d5c17132df9c750fc833d406ead055ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
